const countries = [
  {
    name: "bangladesh",
    district: [
      {
        name: "Dhaka",
        cities: [
          { name: "Dhamrai Upazila", type: "suburban and rural" },
          { name: "Dohar Upazila", type: "suburban and rural" },
          { name: "Keraniganj Upazila", type: "suburban" },
          { name: "Nawabganj Upazila", type: "suburban and rural" },
          { name: "Savar Upazila", type: "suburban and rural" },
        ],
      },
      { name: "Faridpur", cities: [] },
      { name: "Gazipur", cities: [] },
      { name: "Gopalganj", cities: [] },
      { name: "Jamalpur", cities: [] },
      { name: "Kishoreganj", cities: [] },
      { name: "Madaripur", cities: [] },
      { name: "Manikganj", cities: [] },
      { name: "Munshiganj", cities: [] },
      { name: "Mymensingh", cities: [] },
      { name: "Narayanganj", cities: [] },
      { name: "Narsingdi", cities: [] },
      { name: "Netrokona", cities: [] },
      { name: "Rajbari", cities: [] },
      { name: "Shariatpur", cities: [] },
      { name: "Sherpur", cities: [] },
      { name: "Tangail", cities: [] },
      { name: "Bogra", cities: [] },
      { name: "Joypurhat", cities: [] },
      { name: "Naogaon", cities: [] },
      { name: "Natore", cities: [] },
      { name: "Nawabganj", cities: [] },
      { name: "Pabna", cities: [] },
      { name: "Rajshahi", cities: [] },
      { name: "Sirajgonj", cities: [] },
      { name: "Dinajpur", cities: [] },
      { name: "Gaibandha", cities: [] },
      { name: "Kurigram", cities: [] },
      { name: "Lalmonirhat", cities: [] },
      { name: "Nilphamari", cities: [] },
      { name: "Panchagarh", cities: [] },
      { name: "Rangpur", cities: [] },
      { name: "Thakurgaon", cities: [] },
      { name: "Barguna", cities: [] },
      { name: "Barisal", cities: [] },
      { name: "Bhola", cities: [] },
      { name: "Jhalokati", cities: [] },
      { name: "Patuakhali", cities: [] },
      { name: "Pirojpur", cities: [] },
      { name: "Bandarban", cities: [] },
      { name: "Brahmanbaria", cities: [] },
      { name: "Chandpur", cities: [] },
      { name: "Chittagong", cities: [] },
      { name: "Comilla", cities: [] },
      { name: "Cox's Bazar", cities: [] },
      { name: "Feni", cities: [] },
      { name: "Khagrachari", cities: [] },
      { name: "Lakshmipur", cities: [] },
      { name: "Noakhali", cities: [] },
      { name: "Rangamati", cities: [] },
      { name: "Habiganj", cities: [] },
      { name: "Maulvibazar", cities: [] },
      { name: "Sunamganj", cities: [] },
      { name: "Sylhet", cities: [] },
      { name: "Bagerhat", cities: [] },
      { name: "Chuadanga", cities: [] },
      { name: "Jessore", cities: [] },
      { name: "Jhenaidah", cities: [] },
      { name: "Khulna", cities: [] },
      { name: "Kushtia", cities: [] },
      { name: "Magura", cities: [] },
      { name: "Meherpur", cities: [] },
      { name: "Narail", cities: [] },
      { name: "Satkhira", cities: [] },
    ],
  },
];
